### ISSUE TITLE
Several subdomains?

### ISSUE THREAD

**Issue by cbho** [tynor88/docker-unoeuro-dns#6]
Hi,
brilliant to have a Docker container for this - really happy about it.
Is it possible to fiddle with the code in order to have several subdomains validated?
like x.mydomain.dk, y.mydomain.dk, z.mydomain.dk and so on...
(For use with nginx)
Regards,
Chr.

**Comment by cbho** [comment]
Found the answer by trying different approaches - a Docker file with this works:
      - DOMAIN=mydomain.dk
      - HOSTNAME=x
      - HOSTNAME=y
      - HOSTNAME=x
      - HOSTNAME=etc

**Comment by tynor88** [comment]
That definitely doesn't work. This docker only supports one hostname.

I would just start multiple dockers. One for each hostname - they are very lightweight. 

I've switched to Cloudflare, so i won't do any further development on this, to support multiple hostnames.

**Comment by cbho** [comment]
Ok - thanks - looked like it worked - will try as described :-)
